### ISSUE TITLE
[CWL] tries to resolve `File` objects in non-standard extensions

### ISSUE THREAD

**Issue by imilos** [DataBiosphere/toil#3253]
I'm trying to run [this workflow](http://spider.pmf.kg.ac.rs/~milos/broad.cwl) using `toil-cwl-runner`. However, it fails with:

`[2020-10-01T08:30:38+0200] [MainThread] [E] [toil.cwl.cwltoil] Got exception 'HTTP Error 404: Not Found' while copying 'https://api.sbgenomics.com/path/to/input_list-1.ext'`

It runs fine with `cwltool`. I am not really sure why is toil even accessing this link, as this is some test link that should always return 404. Is there a known TOIL workarond for such a situation?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-679)
┆Epic: CWL v1.2 support
┆Issue Number: TOIL-679

**Comment by DailyDreaming** [comment]
@imilos Because it's listed as an input:

```
          "inputs": {
            "input_list": [
              {
                "path": "/path/to/input_list-1.ext",
                "size": 0,
                "secondaryFiles": [],
                "class": "File"
              },
              {
                "path": "/path/to/input_list-2.ext",
                "size": 0,
                "secondaryFiles": [],
                "class": "File"
              }
            ]
          }
        }
```

Toil is probably trying to import it into the jobstore since it's listed as an input and a file.  However, I'm noticing that this says `size: 0`, so my guess is that cwltool has some shortcut where it will just create a file of size zero rather than looking for an empty file?  If that's the case, this would be a straight forward fix.

This workflow is a little unwieldy to look at all at once, so I was curious what this part of the workflow needed this input for and what are expected conditions for an input file to not have to exist?

**Comment by mr-c** [comment]
@DailyDreaming That is part of a `sbg:job` section, which `toil-cwl-runner` would skip due to the `sbg` prefix, so I don't think that is the culprit

**Comment by mr-c** [comment]
I'm guessing it is https://github.com/DataBiosphere/toil/blob/master/src/toil/cwl/cwltoil.py#L1729 and its indiscriminate use of`adjustFileObjs` whereas `cwltool` only calls `adjustFileObjs` is specific situations.

**Comment by DailyDreaming** [comment]
@mr-c Forgive me, I should have linked, as that's the line I was thinking of where we import into the jobstore, which is implemented on all "File" inputs on all jobs.  I hadn't remember it skipping anything with an `sbg` prefix, and because that was implemented before my time, I assumed the implementation was correct.

Under what situations should toil skip importing files (_all_ jobs prefixed with `:`?) and do you have a link to the spec/feature we should be following in this case?

**Comment by imilos** [comment]
Since I got the information that those files are not important at all for the workflow, I try commenting out the lines @DailyDreaming listed and found `cwltool` completing the whole workflow without errors. However, Toil gives:

`	OSError: [Errno 36] File name too long: '/tmp/tmpfc5j3tpw/jobs/kind-https_api.sbgenomics.com_v2_apps_stefan_stojanovic_gatk-germline-wf-dev_broad-germline-wf-local-ver_6_raw_createsequencegroupinglists_ana_d_gatk-genomes-in-the-cloud-2-3-2-1510681135-dev_createsequencegroupinglists_3_createsequencegroupingtsv_ana_d_gatk-genomes-in-the-cloud-2-3-2-1510681135-dev_createsequencegroupingtsv_5'
`
Any advice on what to try as a workaround?

**Comment by mr-c** [comment]
@imilos Glad to hear about the progress! I think that error was fixed recently via https://github.com/DataBiosphere/toil/pull/3230 (but there hasn't been a new release of Toil since then). So you could try installing the latest code from GitHub to confirm the fix.

**Comment by imilos** [comment]
Dear @mr-c, unfortunately, I'm still getting the same 404 error for [this workflow](http://spider.pmf.kg.ac.rs/~milos/broad.cwl) using current git master:
```
toil-cwl-runner --version
4.3.0a1

```

**Comment by mr-c** [comment]
@imilos Pardon me, I [was unclear](https://github.com/DataBiosphere/toil/issues/3253#issuecomment-703501197) ; I meant that the issue with "File name too long" should have been solved by https://github.com/DataBiosphere/toil/pull/3230

You will still need to remove the lines that @DailyDreaming listed until that is fixed in `toil-cwl-runner`

**Comment by imilos** [comment]
@mr-c thanks for your quick response and your help! I can confirm that "File name too long" no longer appears. However, using this [inputs.yaml](http://spider.pmf.kg.ac.rs/~milos/inputs.yaml) I'm now getting:

`schema_salad.exceptions.ValidationException: Not a file URI: /home/user/sbg/broad/H06JUADXX130110.1.ATCACGAT.20k_reads.converted.pe_1.fastq`

The input files listed in `fastq_list` exist on the mentioned path. Any suggestions? Perhaps I should open another issue?

**Comment by mr-c** [comment]
@imilos You are welcome!

`/home/user/sbg/broad/H06JUADXX130110.1.ATCACGAT.20k_reads.converted.pe_1.fastq` is indeed not a URI. Is this from the input object?

You will need to use `location: file:///home/user/sbg/broad/H06JUADXX130110.1.ATCACGAT.20k_reads.converted.pe_1.fastq` or `path: /home/user/sbg/broad/H06JUADXX130110.1.ATCACGAT.20k_reads.converted.pe_1.fastq` but not `location: /home/user/sbg/broad/H06JUADXX130110.1.ATCACGAT.20k_reads.converted.pe_1.fastq`. That is to say, for all `class: File`, `location` must start with `file://`, `http://`, `https://`, or `ftp://`.

**Comment by imilos** [comment]
Dear @mr-c, thx again. I already tried all these combinations of absolute paths prefixed with `file://` and without the prefix. No luck. It seems that `fastq_list`gets preprocessed somehow and the prefix gets stripped out since even with a prefix I get the same error:

`schema_salad.exceptions.ValidationException: Not a file URI: /home/user/sbg/broad/H06JUADXX130110.1.ATCACGAT.20k_reads.converted.pe_1.fastq`

On the other hand, all the combinations work well with `cwltool`.

**Comment by mr-c** [comment]
Looking again at [your input object](http://spider.pmf.kg.ac.rs/~milos/inputs.yaml) I see non-standard fields that aren't namespaced as they should be. Can you remove the `metadata` sections from under the `class: File`s and try again?

**Comment by imilos** [comment]
You are right. The metadata from the input object is used in [the workflow](http://spider.pmf.kg.ac.rs/~milos/broad.cwl) within the javascript expression (line 14135). Perhaps I can try to hack on that code to add a required necessary prefix `file://` or maybe you have better advice as a CWL expert?

**Comment by imilos** [comment]
Hi @mr-c, just to say that last evening I tried if anything changed since last pull from the master. It tursns out that my workflow started working with the latest commits :) I don't know what exactly has been changed, but thanks a lot for your help and keep going with a first class CWL support!

**Comment by mr-c** [comment]
Huzzah! @DailyDreaming has been making CWL related fixes, so I'll forward the credit to him.
