### ISSUE TITLE
Toil is unable to import HPRC assembly

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#3366]
I can download it just fine from the command line
```
aws s3 cp s3://human-pangenomics/submissions/fc721e22-1ce2-4d38-bf88-72cf231bcb90--UCSC_2020AUG_assembly/2020AUG26_upload/HG02109/HG02109.mat.fa.gz .
```
but Toil can't import it
my script
```
from toil.common import Toil
from toil.job import Job
if __name__=="__main__":
    options = Job.Runner.getDefaultOptions("./toilWorkflowRun")
    options.logLevel = "OFF"
    options.clean = "always"

    with Toil(options) as toil:
        toil.importFile("s3://human-pangenomics/submissions/fc721e22-1ce2-4d38-bf88-72cf231bcb90--UCSC_2020AUG_assembly/2020AUG26_upload/HG02109/HG02109.mat.fa.gz")
```
my command
```
python import_test.py
```
the result
```
Traceback (most recent call last):
  File "import_test.py", line 12, in <module>
    toil.importFile("s3://human-pangenomics/submissions/fc721e22-1ce2-4d38-bf88-72cf231bcb90--UCSC_2020AUG_assembly/2020AUG26_upload/HG02109/HG02109.mat.fa.gz")
  File "/home/hickey/dev/work/toil-import/venv/lib/python3.6/site-packages/toil/common.py", line 1028, in importFile
    return self._jobStore.importFile(srcUrl, sharedFileName=sharedFileName)
  File "/home/hickey/dev/work/toil-import/venv/lib/python3.6/site-packages/toil/jobStores/abstractJobStore.py", line 301, in importFile
    return self._importFile(otherCls, srcUrl, sharedFileName=sharedFileName, hardlink=hardlink)
  File "/home/hickey/dev/work/toil-import/venv/lib/python3.6/site-packages/toil/jobStores/fileJobStore.py", line 302, in _importFile
    sharedFileName=sharedFileName)
  File "/home/hickey/dev/work/toil-import/venv/lib/python3.6/site-packages/toil/jobStores/abstractJobStore.py", line 322, in _importFile
    size = otherCls._readFromUrl(url, writable)
  File "/home/hickey/dev/work/toil-import/venv/lib/python3.6/site-packages/toil/jobStores/aws/jobStore.py", line 444, in _readFromUrl
    srcKey.get_contents_to_file(writable)
  File "/home/hickey/dev/work/toil-import/venv/lib/python3.6/site-packages/boto/s3/key.py", line 1662, in get_contents_to_file
    response_headers=response_headers)
  File "/home/hickey/dev/work/toil-import/venv/lib/python3.6/site-packages/boto/s3/key.py", line 1494, in get_file
    query_args=None)
  File "/home/hickey/dev/work/toil-import/venv/lib/python3.6/site-packages/boto/s3/key.py", line 1526, in _get_file_internal
    override_num_retries=override_num_retries)
  File "/home/hickey/dev/work/toil-import/venv/lib/python3.6/site-packages/boto/s3/key.py", line 355, in open
    override_num_retries=override_num_retries)
  File "/home/hickey/dev/work/toil-import/venv/lib/python3.6/site-packages/boto/s3/key.py", line 315, in open_read
    self.resp.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>822E12E6DAE082D9</RequestId><HostId>e0oz7J3ehvimfEgUiYZshZmze8xBNyz+QacFq/LJ1jG9hsZWsR3WtOko6rMTGb8AoPqmLLaSMtk=</HostId></Error>
```
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-743)
┆Issue Number: TOIL-743

**Comment by DailyDreaming** [comment]
This and #3367 should both be fixed by the move from boto to boto3 in the AWS jobstore.  Will be addressed next sprint.

**Comment by DailyDreaming** [comment]
@glennhickey This should be fixed now that #3400 has been merged.  Could you test this?

**Comment by DailyDreaming** [comment]
Closing, please reopen if this is still a problem.

**Comment by glennhickey** [comment]
I tried launching a cluster with 
```
TOIL_APPLIANCE_SELF=quay.io/ucsc_cgl/toil:5.3.0a1-bfe766f5c82f2c6d3339d7165eec0e3e6931bb06-py3.6
```
This issue persists.  I'm also concerned that it took nearly 2 minutes to do an S3->S3 (using s3 jobstore) import of that first file -- usually this is about 10 seconds on 4.2  

```
 grap-origseqs.log --batchSystem mesos --provisioner aws --nodeTypes r3.8xlarge:0.7 --maxNodes 25  --refFromGFA hg38
Deprecated toil method.  Please use "toil.statsAndLogging.set_logging_from_options()" instead."
[2021-01-23T15:30:51+0000] [MainThread] [I] [toil.statsAndLogging] Importing https://s3.amazonaws.com/nanopore-human-wgs/chm13/assemblies/chm13.draft_v1.0.fasta.gz
[2021-01-23T15:32:34+0000] [MainThread] [I] [toil.statsAndLogging] Importing s3://human-pangenomics/submissions/fc721e22-1ce2-4d38-bf88-72cf231bcb90--UCSC_2020AUG_assembly/2020AUG26_upload/HG002/HG002.mat.fa.gz
Traceback (most recent call last):
  File "//venv/bin/cactus-graphmap", line 8, in <module>
    sys.exit(main())
  File "//venv/lib/python3.6/site-packages/cactus/refmap/cactus_graphmap.py", line 95, in main
    runCactusGraphMap(options)
  File "//venv/lib/python3.6/site-packages/cactus/refmap/cactus_graphmap.py", line 164, in runCactusGraphMap
    seqIDMap[genome] = (seq, toil.importFile(seq))
  File "/usr/local/lib/python3.6/dist-packages/toil/common.py", line 998, in importFile
    return self._jobStore.importFile(srcUrl, sharedFileName=sharedFileName)
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/abstractJobStore.py", line 303, in importFile
    return self._importFile(otherCls, srcUrl, sharedFileName=sharedFileName, hardlink=hardlink)
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/aws/jobStore.py", line 424, in _importFile
    srcObj = self._getObjectForUrl(url, existing=True)
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/aws/jobStore.py", line 502, in _getObjectForUrl
    region = AWSJobStore.getBucketRegion(bucketName)
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/aws/jobStore.py", line 1570, in getBucketRegion
    loc = s3_boto3_client.get_bucket_location(Bucket=bucket_name)
  File "//venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "//venv/lib/python3.6/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied
(venv) root@ip-172-31-23-134:/work# aws s3 cp s3://human-pangenomics/submissions/fc721e22-1ce2-4d38-bf88-72cf231bcb90--UCSC_2020AUG_assembly/2020AUG26_upload/HG002/HG002.mat.fa.gz .
cancelled: ctrl-c received                               
```

**Comment by glennhickey** [comment]
I don't seem to have the ability to open closed issues...

**Comment by glennhickey** [comment]
One more comment,  Just reran the same job on toil 4.2, but with copied output and got
```
[2021-01-23T15:55:19+0000] [MainThread] [I] [toil.lib.bioio] Importing s3://vg-k8s/vgamb/wg/cactus/GRCh38-freeze1/fasta-masked/chm13.draft_v1.0.fasta.gz
[2021-01-23T15:55:23+0000] [MainThread] [I] [toil.lib.bioio] Importing s3://vg-k8s/vgamb/wg/fasta/GRCh38-freeze1-copy/HG002.mat.fa.gz
```
In my log.  so to import the first file took 4 seconds on toil 4.2 vs. 103 seconds on toil 5.3

**Comment by glennhickey** [comment]
I humbly retract the previous comment about the running time being higher on 5.3.  I'd unwittingly used a different bucket between runs.  Sorry!

**Comment by adamnovak** [comment]
@glennhickey It sounds like there's no actual issue here anymore. I just tried running `import_file.py`, and it prompted me for MFA and then finished without complaining. You also say import in 5.3+ isn't actually notably slower at it compared to 4.2. So I'm going to close this out.
